### ISSUE TITLE
Broken symbols if gzip encoding are used

### ISSUE THREAD

**Issue by kerbyj** [rhaidiz/broxy#1]
If the server uses gzip compression, the user will see an unreadable response body when using the repeater.
![gzip](https://user-images.githubusercontent.com/31669858/74472311-c38a7e00-4eb2-11ea-8139-794bf65e33f2.png)
![not-gzip](https://user-images.githubusercontent.com/31669858/74472320-c84f3200-4eb2-11ea-8646-8a86eb58dfbd.png)

**Comment by rhaidiz** [comment]
Yes, that is a known behavior since at the moment there's no option that automatically deals with the compression. The core proxy does it automatically because, at the moment, I'm using the vanilla version of goproxy. This will change with the next iteration.

**Comment by rhaidiz** [comment]
I have finally released the version I was working on and this issue is now fixed.
