### ISSUE TITLE
Cannot write TLS reponse header

### ISSUE THREAD

**Issue by sir-marv** [rhaidiz/broxy#5]
I'm getting lots of cert errors. I've saved the CA from within broxy and imported it into firefox. 

Example error:
2020/07/04 14:07:20 [095] WARN: Cannot handshake client github.githubassets.com:443 EOF
2020/07/04 14:07:20 [081] WARN: Cannot write TLS response header from mitm'd client: write tcp 127.0.0.1:8080->127.0.0.1:44238: write: broken pipe

**Comment by rhaidiz** [comment]
Those warnings come from goproxy. I'm not sure what's causing them but you can ignore them, they shouldn't impact the ability to analyse the traffic.
